# Generated by Django 5.2 on 2025-04-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('MPesa', 'MPesa'), ('PayPal', 'PayPal')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('qr_code', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
